name: spells

environment:
  sdk: '^3.4.0'

dependencies:
  objd: 
    git:
      url: git@github.com:ValiantChip/objD.git
      ref: master

dev_dependencies:
  build_runner: 
  objd_gen:
    git: git@github.com:ValiantChip/objd_gen.git
